export const tipoEvento = [
  { area: "Gerencia", value: "Gerencia", disabled: true },
  { area: "Gerencia", value: "Reporte" },
  { area: "Gerencia", value: "Cambio de aceite" },
  { area: "Gerencia", value: "Mantenimiento" },
  { area: "Gerencia", value: "Repuesto" },
  { area: "Gerencia", value: "Combustible" },
  { area: "Gerencia", value: "Cambio Llanta" },
  { area: "Gerencia", value: "Reparacion Llanta" },
  { area: "Gerencia", value: "Reporte Varios" },
  { area: "Gerencia", value: "Pago Servicios" },

  { area: "Administracion", value: "Administracion", disabled: true },
  { area: "Administracion", value: "Reporte Diario" },
  { area: "Administracion", value: "Cambio de aceite" },
  { area: "Administracion", value: "Mantenimiento" },
  { area: "Administracion", value: "Cambio de aceite" },
  { area: "Administracion", value: "Combustible" },
  { area: "Administracion", value: "Repuesto" },
  { area: "Administracion", value: "Cambio Llanta" },
  { area: "Administracion", value: "Reparacion Llanta" },
  { area: "Administracion", value: "Reporte Varios" },
  { area: "Administracion", value: "Pago Servicios" },

  { area: "Seguridad", value: "Seguridad", disabled: true },
  { area: "Seguridad", value: "Reporte Varios" },

  { area: "Medio Ambiente", value: "Medio Ambiente", disabled: true },
  { area: "Medio Ambiente", value: "Reporte Varios" },

  { area: "Supervisor", value: "Supervisor", disabled: true },
  { area: "Supervisor", value: "CheckList" },
  { area: "Supervisor", value: "Mantenimiento" },
  { area: "Supervisor", value: "Cambio de aceite" },
  { area: "Supervisor", value: "Combustible" },
  { area: "Supervisor", value: "Repuesto" },
  { area: "Supervisor", value: "Inicio Servicio" },
  { area: "Supervisor", value: "Final Servicio" },
  { area: "Supervisor", value: "Cambio Llanta" },
  { area: "Supervisor", value: "Reparacion Llanta" },
  { area: "Supervisor", value: "Reporte Varios" },
  { area: "Administracion", value: "Pago Servicios" },

  { area: "Conductor", value: "Conductor", disabled: true },
  { area: "Conductor", value: "CheckList" },
  { area: "Conductor", value: "Mantenimiento" },
  { area: "Conductor", value: "Cambio Llanta" },
  { area: "Conductor", value: "Cambio de aceite" },
  { area: "Conductor", value: "Viaticos" },
  { area: "Conductor", value: "Combustible" },
  { area: "Conductor", value: "Cambio Repuesto" },
  { area: "Conductor", value: "Inicio Servicio" },
  { area: "Conductor", value: "Final Servicio" },
  { area: "Conductor", value: "Reporte Varios" },
];
